export const FETCH_GAMES = 'GAME/FETCH_GAMES';
export const FETCH_GAMES_SUCCESS = 'GAME/FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_FAIL = 'GAME/FETCH_GAMES_FAIL';

export const ADD_GAME = 'GAME/ADD_GAME';
export const ADD_GAME_SUCCESS = 'GAME/ADD_GAME_SUCCESS';
export const ADD_GAME_FAIL = 'GAME/ADD_GAME_FAIL';

export const CLEAR_STATUS_GAME = 'GAME/CLEAR_STATUS_GAME';
